### ISSUE TITLE
Upgrade index page on reports

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/nhs-covid-vaccination-coverage#77]
Since the children's dashboards went live the index page has been downrated to the third option in the drop down. Can it be promoted to the first option?

![image](https://user-images.githubusercontent.com/40460354/181211196-cc07242b-112d-452e-b683-b393cce29773.png)

**Comment by LisaHopcroft** [comment]
I asked about this before - there isn't a way to specify order, they are listed alphabetically. We could rename appropriately to force them into the correct order? I think renaming to this would work:

1. Vaccine Coverage Index
2. Vaccine Coverage (≥16): 1st dose 
3. Vaccine Coverage (≥16): 2nd dose 
4. Vaccine Coverage (≥16): 3rd dose or booster
5. Vaccine Coverage (5-15): 1st dose
6. Vaccine Coverage (5-15): 2nd dose

**Comment by LisaHopcroft** [comment]
OK, that doesn't work, but I'll work something out that does!

**Comment by LisaHopcroft** [comment]
![Screenshot 2022-07-27 at 10 44 46](https://user-images.githubusercontent.com/54442530/181217001-1d881989-31aa-49fc-b78f-1bd2f9f49d54.png)

**Comment by LisaHopcroft** [comment]
Looks like this has @brianmackenna's approval, so I'll close this issue.
